addition of link to Rosvita Beta LICENSE and addition of "docker pull" exit status check

diff --git a/downloads/get_rosvita b/downloads/get_rosvita
--- a/downloads/get_rosvita
+++ b/downloads/get_rosvita
@@ -2,6 +2,10 @@
 
 echo -e "   _  __                __\n  | |/ /___ _____ ___  / /___ _\n  |   / __ \`/ __ \`__ \/ / __ \`/\n /   / /_/ / / / / / / / /_/ /\n/_/|_\__,_/_/ /_/ /_/_/\__,_/\n\nROSVITA Installer v0.1\n"
 
+echo "Before installing ROSVITA, please read the ROSVITA license agreement:"
+echo "https://raw.githubusercontent.com/Xamla/docs.xamla.com/gh-pages/rosvita/downloads/LICENSE"
+read -p "Press ENTER to continue or CTRL+C to cancel"
+echo ""
 echo "In case of any problems with the installation please visit: https://discuss.xamla.com/"
 echo ""
 
@@ -37,8 +41,14 @@ echo "The ROSVITA image will be downloaded from Docker Hub, press CTRL+C to canc
 read -p "Press ENTER to continue"
 echo "Getting ROSVITA from Docker Hub.."
 sudo docker pull xamla/rosvita:latest
+if [[ $(echo $?) != 0 ]]; then
+   echo "Could not download latest ROSVITA image. Please check your internet connection and disk space."
+   echo "If the problem does not go away, we are happy to help you at http://discuss.xamla.com."
+   exit 1
+fi
 if [[ $(sudo docker images | grep -c 'xamla/rosvita') == 0 ]]; then
-   echo "Could not download ROSVITA image. Please check your internet connection. If the problem does not go away, we are happy to help you at http://discuss.xamla.com."
+   echo "Could not download ROSVITA image. Please check your internet connection and disk space." 
+   echo "If the problem does not go away, we are happy to help you at http://discuss.xamla.com."
    exit 1
 else
    echo "ROSVITA image has been downloaded successfully."
